apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../infrastructure/helm-installs/cert-manager/local
  - ../../../infrastructure/helm-installs/ngf/local
  - ../../../infrastructure/helm-installs/grafana-alloy/local
  - ../../../infrastructure/helm-installs/cnpg/local
  - ../../../infrastructure/helm-installs/redis/local