kind: Secret
apiVersion: v1
metadata:
    name: loki-credentials
    namespace: grafana-stack
data:
    GRAFANA_CLOUD_TOKEN: ENC[AES256_GCM,data:k8wW0DjxX2oX77kEIRyl172MPiI+VnE5z/Q//D3UboxTlk/khqis4KsocflWlLS06EFJDT062dsRlQubYtrU5TQ9c4ZDgAS16vU/etB9DkwtGlfbd5Sm2ZXVOkqF9TID2H3YIv+HZo48IDy18w6lfSTJVfts5IRquakzDJv7/QPMYx1OTvHhAQoFCq+iWUvZoonX3ZCJcJfKxON22ybNAyXqrafHRK9jPTpSr6JThSjF+qv6+8WGxXgHjY/nTiHUN5LDM/mSpOVZC+IwueZaiw==,iv:mEpiXRd+6wioCd4NYCMLeOOnQhgxSqb8TpRen3U7WPw=,tag:2mQZ8jFFKxN63mdphHZF3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-09-12T09:43:12Z"
    mac: ENC[AES256_GCM,data:9XFSx4ak3dTgxynSTpp53zDvMc1n4qblud4iXqQ5dfYYOd/UeAExCkuoddKZKH1v0J6BhIFSCXB4hj28RKqsvvL7OThYqt9HCpFMRQ6c/DLAAm37xuhmBPK7BMbCXmwPNqDY6uf0+vdQmF1mPg+710s+Zymwp1v2r7JkXQXftTc=,iv:KpelzObiUL8XLya/uPKxDLK2F9hdNSwBGq7DrJ2engI=,tag:up/4AU/vW0x4nA6qznoNuA==,type:str]
    pgp:
        - created_at: "2025-09-12T09:42:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7HkzTbKNKEvAQ/+KyrBBAppSTsGRgpor68uCwRgNGbRPRoSgeWYJZeyFJeQ
            sSuNljuLs/vMTOHwnGBEJPDA2vji2BAbiYCeMLPv1Xcx7xWnMFsRdLLRp/8vz+59
            XXdWFEuhne04lTQ5DBOOJaboLngQ4Vm5Yx1ZtvEXhg94+MUaHn+QEeBVBhlRfLI0
            4HMpm53ePInWjTk8ZWPRkE6l314h/GslP8SL/b5iDCyJeIy6Uh220NBI1ahEythM
            CS+SE8hbdqjzAntizJ7LwF3IpzPEtdHKJGk2DVk049oWnyUilT5ZWXb7I5zpUe/Q
            nMax6Z+kWpTlOqa0lLhh6RRlVVGhrH1R4MQ404Ehpo8OOLoK1D1iVNzi4AeqmmJE
            Prg0LCgRSH4XEp8yYcvVMHEvb4AiOS/dzUBQ++qJ/RNwhw9bMjTJMu8bmwZcq3Zy
            xbN9aufgVs3F6FpLlc4CPYPgD/lyXnahXHLHVxAqYZRdbxRqJUYlaqW3Uq/ikTfK
            GvS0FdHWANdmJwY7YsMP443pho4YyDRls5iZMguZuscH/eR0Mt1IIat4CBkl34vX
            JWu1b4b0j1preSsNCXzOup2+XObTD9FNPahwHxXsAPZ2V0WAwAFrresjpYykGdtZ
            Am+HsrSgS/rxHQgG6FoV+DzeyZGqklsb8wqHYBRBrIZn3geCrclxqPkr8bxu3QrU
            aAEJAhCHiHD2eVFeLBTf6BummoeUHPscopH15Rqn0ALPvJBUhfctnhoBE7j0isXf
            QajuurjrA7b1lKj2LPNzeaEoJySFlclBxw+9rZiBJRaT48j8JU2Y7rEq4p4Zkeqq
            9cKaCjRQllVf
            =S1bM
            -----END PGP MESSAGE-----
          fp: C2C715BB173803D1A33C0B9E64D72306B5CEADB8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
