apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nginx-gateway-fabric-repo
  namespace: flux-system
spec:
  interval: 168h
  ref:
    tag: v2.1.1
  url: https://github.com/nginx/nginx-gateway-fabric