kind: Secret
apiVersion: v1
metadata:
    name: loki-credentials
    namespace: grafana-stack
data:
    GRAFANA_CLOUD_TOKEN: ENC[AES256_GCM,data:mho+BlaGx1gSpCe7g8fyz/QVhnTtaXKalFZ7F2S+JWUBRzCi7kB3crKJon4Hh3nbylx/76vFDrX6u6Qa2ZYF+x58hlOEnA6RjzXPsPqhRLcMKps/f8TGsFae1UHUh1s9Yc/0/t9nS/6ZniVTA/bmMw48l16U37kAo0oq+rT51vHQlGV81iQ6fKhH58gAewrqFTO6VPcsfK/koG9ozJZ47Yugg7+bhcNPRBdyfId/0wt0vaesiWzfNU/nx5M32GtD9DLASo4VVYvaT6sTq7+pIA==,iv:cKhklHS5q1APPSDLEaI1m+oFIdop3pUVlmZvxzkZHjw=,tag:sZjGpculsczOJUt9WbZFZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-09-15T09:55:02Z"
    mac: ENC[AES256_GCM,data:JbhipwOQwqsvSxfbdhBHHLtFaPxicKaWeUIJrdgIVHHfNcE8rnX9PL4MQlfXjmy3KqBthqhi0YDHgLYBefbp+7TrSx6ZekdnyG7sRjmiTdkzCOm31Nd92vzU6JnmEQWEbetrtwdW+jcPDzLkWvJg5Y0JqqVkTec/X2RyBm0e5gA=,iv:CCf6nCb8PhKRtkyTCEIASdGvou4J2+py5l9GAvWCBFo=,tag:1TQumqcFVHQZJ8uT9Z2o4A==,type:str]
    pgp:
        - created_at: "2025-09-15T09:55:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5kkSf0WUgyKAQ//bwV7TFIzsUEXBfRE6+FM834E/dd1Js1x9sUuARP1pApk
            iUaX3PDPQw8LlCVtocfQNL5pC0P6iqoT4y5a6dH44zAkUxQ+qcXkzC6yN9HmBNpL
            lbsEcUJeSF8UcpnKImd25nBpJ7qnYqTt/YTW03SyPyCXK0dMQESemDntG+fCCfVq
            pJPLS18BBpBLHhXj9QZOv6dOVwVYOQUaXCnTA5a3wQVPmdu8o+lbwQHUCsGPAMKq
            CRzESemXmSHaR0NWecFbVRHEe4xkJ3TAgSkFdYJPaYA40F2YPT9qZ6HilB/OKxuL
            QPxnpzMjTqYAa0pTjidUMTsX0/q9rLXyjLRQdpqXdFKZo6LBcKwRX7i14ZiGAF9Z
            1TdXGc3HZq8kk48wIxODTUB7QE7hKVPKnZ6XbP30g92j0z0aX+SZk4ULiOv7ZCAV
            X24VZfcmkdDiSked+9kUK4JCa29jjxhqAQJ2gQH4zzmxpgrizR78+WZ3q1UGO0Ph
            txldkJQkgF+b9vpX/v4tS2i/+toX97+YF7kZLcGfFDx2lFnTju9Uz7y59weNR+Xc
            2FRNoLpq8NL2i2SRhU1PL3ER+mIae24UPzIYKi02dUHUyY/akeNQNVIG3FcnN3Lf
            iasNc+i4ShftQShOD+T9K7xubxQGKIH5ki3A0bSHm3GewCQXoh+MOdYi8x+bxvzU
            aAEJAhAztBhFKpAmHbY37oAeo1+l71Cj6aZN+TfvxV3+LmzuSaLDgHnJ2Tp/f8lO
            bmSXWKqD47ayWO491dEhRACb3V7bC3pFIyQJK250h2UJ8jWTaVmS5QZkD/dwZQuL
            VhZOfILHqxxp
            =EuyD
            -----END PGP MESSAGE-----
          fp: 4527EAAAEF676E9D3802CB489BCD8CD0C1B5A8CE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
