apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 12h
  values:
    controller:
      annotations:
        service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: 'true'
        service.beta.kubernetes.io/do-loadbalancer-hostname: "lb.devcraft.nl"
      replicaCount: 2
      service:
        type: "LoadBalancer"
        externalTrafficPolicy: Local