apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-installs
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: helm-repos
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/helm-installs/production
  prune: true
  wait: true