apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-secret
data:
    username: ENC[AES256_GCM,data:/LE8CbslcbYNbXIP,iv:uAUzIlOinBd+0KJWZyPa53J607Hl+poUEvaP0OjxdGQ=,tag:VJukbiAUJyZQp2s6IDi1pw==,type:str]
    password: ENC[AES256_GCM,data:lv5+BKQX3TTHiZxkrZnkqPYOCbLwjNDIBOZTDy0aHA9UgZr7vkYZS6i6j587mmHw8zl9PnRPTKDhFBNcGFqE6ngY368BGupQTYuGPUMnis/eolmA4qLUSDmpVruiz0QcZeSv870pB5CPlvo8oUGpk0hCjSboo5kpFBtj/TgmmIpzicXpHKvBNZtWv8UBh6ged84TuLUSsqyDMs7rKo/kAfZFgtqMcbrv9o6QUw==,iv:j093E2Rku90E0BBlGQ5vLuPHxIcV5jJqqDDSCHXKCRc=,tag:BQgBZqvF9XoHv9CMp4tQjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-09-24T06:54:10Z"
    mac: ENC[AES256_GCM,data:d/12ErJSH0oBmvSHFXgfR+WuqFKlI+8GzYdbCarqlA+LTjE+5y+66dXl5fuSm8PXNHyaMMyWVNb12VJR02+68OzHh/FI78eDItU2eKfXDWtT3TiThe6UdAWf3q7VY4orq5sf7Azx7LjQ1ur4V1ZMXBE9zleo5U5Q2tx64bAEtmw=,iv:lImanw07/B6cuNpCtWIWJRN64yGWoqIGj0T7NsIcm/M=,tag:ZpHWvYwP7Lb8tY7Cfu+zNg==,type:str]
    pgp:
        - created_at: "2025-09-24T06:54:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5kkSf0WUgyKAQ//dfTqxjlfDlMzK+gDw4zBWdMjGhO+nWQc6ka8PtJG8CCY
            aA78kr4Sg8OVkDB1U6hi4f5+G5/Stz1r1TqKU1PccMvZNAbhTLOmHbTly8X6C2n2
            m1s3icXIq7as3vz0fEaDJ7vLIlWLP7zMDgL9sIEpt4hFqcFntr3m7gXiY7rihsby
            Cqw/7caqdVdPBlKa/PzArrhk8TRRs5ZsxoY7cbWdsCavGSxsJ0G8+gdEv4G/VgHO
            EVrFGNDxgJb50QqkSTzb79Un4ewk0/u65V5H8pTjQPcD7hp07bz/tMAgTb8wGpAg
            OFrExEdbkVn6pDApZCeMG3lT5wE0ZmyMpURdLx8YEM8XoMaOXff2CACU5K1nj3K1
            8hE0ly9nu2Rvw3UsNkMwA6jYOwzRp/QysmiiJizjZChICiw/udjTpZ1BJzstm7p1
            qK1j4PJRzZpvyKpGRg9TWqyCOPp112qCDWOeLWvJJXLXoJEbALv/9mzHqArGr23r
            LIiOmiI1ONVaYqox5ff79VuU3n+SIpyuRMZasRL7Y0N+KFoBhsnREMEdUGkWgMYc
            LGzo0A8YgMh5N0YG1cDORdjfywpKAAQHcVBKmswJf/sQ5rqFtwaG6byeR92GcEFY
            zThDb8DOqZbiQ5AgjD7A37G12oXDYxzsVar4TPJUDAhqljyahd2gpCjk+EB0p6PU
            aAEJAhB9JFJ7WM116LnNFviRsVXIvPP5MWA2YzAFOIHLJmkLSR0a+RqySM0FcejD
            HEjZa9dVyQGgLTpCFWYUWYsFbvQkLBReuTTACY/zWx3FKYmQi0iagsKMMVtLfCsF
            zQv68hL0bzYK
            =wDCM
            -----END PGP MESSAGE-----
          fp: 4527EAAAEF676E9D3802CB489BCD8CD0C1B5A8CE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
