apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-secret
    namespace: keycloak-operator
data:
    password: ENC[AES256_GCM,data:VnUe4+KqY4Ng9T1m7bzhDHA330vRng9KSgWCAY0g1AXlZ7l951j1Ba7YM/L+kxpdXOvZFOoW5jPncRMkNsd6hHVWuQ7qSXasWk9aKvx8uJK++JtF6X4ULfWUqXH1T0oG3CfuMG9lsM0ejSGEgKBlwZVHNDUxYD+dkULf84Kp/wVc9S6bi1izAOeF/RQ0oNKpO+HwizsMU9pk68o4jl/b7GQ3tC72fsisF4YKdQ==,iv:rtebl0B+IVJcwecssXlIBCiaEIA7UipZ017nWmElAzo=,tag:IwX7TXHy8O5xw2gEMeJIqQ==,type:str]
    username: ENC[AES256_GCM,data:ftHJhPkE6LA=,iv:M3mfj53Tc++tudjyims0Kmf39Mrxb8p4tRvkzsEzoNg=,tag:dScTyBKetg8Sr+VQO6ShCw==,type:str]
    client-id: ENC[AES256_GCM,data:H64FzDXE0aTHyMNujpx6W0LAuXI=,iv:ovVYiuUN6r/iqrqpIEeaI2CrjQkrX7b87L9iFkWzJMc=,tag:RvjKuKUlKf+jaX7NlFoV5w==,type:str]
    client-secret: ENC[AES256_GCM,data:VU/dNNotqr4FxVwwlERyqqboLnytelvFBwSvMzGUNZIPJfqhy+oP8Be4FMdjmlCm,iv:ZzXZk1z1eQ1Y79lV0WwBBJBEIKpXImljMolBWoJmPUU=,tag:7IqIDzplaZg9PznTaxAWVg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-09-25T12:42:36Z"
    mac: ENC[AES256_GCM,data:ufGfUy5oK6UXqz3sp5Cse+hwtp+rt4im8x9Ti0ufEQNKsFErMS4CbLbpk0zJSrDGttiU1wwea8LXiXKwmmgrZr1hSzRvqHEi7lFxLBCtZdAVqU7cpL6wAV0SGKyvaa+Ar4bG1gRkVH7GS6kU4i2cHpARgGYcx2YGXGcQI4z1p7g=,iv:CT72KMMXWAPgIVFK6PPN93XjqM1yku9tcTs31fnPytU=,tag:sxrqTVcZfeOfBBgeNsBZLw==,type:str]
    pgp:
        - created_at: "2025-09-25T12:42:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5kkSf0WUgyKAQ//cL0Kk8RoRMNSdEusal/b98VAdgwbGaC3QKCxO4TWzEMV
            al5V3aGE9Xa2BubvKpr1BP+N17sSpQ6q2ptuDUfVbyUiu2RQ/0DeO2ZfewGZqDgC
            nnADYnaXtVqEEVHtfE6H272Kgknen7/uX/5HdtQbgXMzLi1BUfmYy/RmPa+jr4Df
            6VgA6RnJTh6/VG2DChc66RCJDrMUydfL9Zy79MSZkdNoOe1N3ewiu9fnb1oMHxZe
            PVJfgOTzwQeRbzHSzUcWt1GZyrMq3pb9cE2mCPFgo/ZD800ax9Ol4/Ky9AMUEM3d
            hGD9bhCeqMQijR1mv/77wTpwlM17w/7/rlb6eF+5HgvE2wJvPaElaX+bLuoZOyOR
            4el0W303Y/ZCaUt5v69OVgDZNPA3mdd20bENsrvjH1yv7DuGUDXi7Iec38c9TJqi
            U17l6BIeVlpRJXyGVyoMU0wVv/FeXZqkN1GDuG2UxOBhmM0jb3XBD15N/ZC9RCvk
            yagGFOy6XxXAh7t3X0OPwgABmTfGNFLJ2kMMvpZt1LH61QHa7BEeQ4g6BIvO9MZ6
            o5C1E/AC8oTsRxm+cEBAYRDm/AiJp1azg6KXeD+fV6pndJt2mlErjsYxRojzAFuh
            siix6BCeWGfezGh6ilWBzXY5XwGb93lOUseEIo5i1+Nnqpa0/hlmN+eBbgSYFenU
            ZgEJAhC5bTCOdPGAWQ8mExVT6aAwXpbpaG0rhN6rIy+s9430eSLk3VTMqvGDsFPi
            SHn+ANESDalfjyDwpOomOEa8iRncQL8lIxI0iS8fVeRY5QoSbBUKof5ke026ox9J
            3WgEOFX3mA==
            =uVjR
            -----END PGP MESSAGE-----
          fp: 4527EAAAEF676E9D3802CB489BCD8CD0C1B5A8CE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
