apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak-operator
resources:
  - db-secret.yaml
  - sa-user.yaml
  - keycloak-admin-secret.yaml
  - kubernetes.yml
  - pg-cluster-keycloak.yaml
  - kc.yaml
  - route.yaml