apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ngf
  namespace: nginx-gateway
spec:
  interval: 12h
  chartRef:
    kind: OCIRepository
    name: ngf
    namespace: flux-system
  values:
    nginxGateway:
      gwAPIExperimentalFeatures:
        enable: true