apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-secret
data:
    username: ENC[AES256_GCM,data:yZ4SxvSuDoLDI0DG,iv:BYZsMzrswN+fwRMeJ1gyks6EXYnRUk0GLrFsqal5zds=,tag:yjCHoR4CmyzfocfeWJ5uKw==,type:str]
    password: ENC[AES256_GCM,data:L5h06B/mv8b60IYWsf/5/yHCJsoRqdnmt3VkS4Jey4Rvy/pSUsXLBLp8TVbvppVoFWRTZ/w6M9m5boaT6qhyXvhbNeX/IXI9VPqWXHNvHFaVYbHtSTFgjG20LkNYfg0V+Z9dllTT6OeynJLyzMIxqrRHQrXIfei+C46tHL3Tqu2j2FLCTAFiWFkXL3nxV4CDFYISjRaBIrJD/6g0P+aK0J2hY0gEn+W2CORM7Q==,iv:8t6NclITs11v7F0Q2aS+L8vH6bwoXksj5I7JWBSLSTI=,tag:HHPN0itR7TqMNhY4y4IgZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-09-22T12:08:12Z"
    mac: ENC[AES256_GCM,data:Zfc9M9LvLj0nZOjStZjwvu3gr2M4JX3+Ximy4gjav7aX5QieS+zhKYOBsgUVXWq37poSThGTL69BaHGlsDwvcl1VPAvUCS/0WuXOTFeqXiOYUE/JQE2LNfJmprdfAbKTkE9DfkHaSZ8Fqiw9RvRvWA4m2PTNkEW3rfQvWSL2u1c=,iv:Rmw4ODezSSlPNPB0w1m6PcIs7sCBBsnOjvuNT9wbG3A=,tag:jMZysjBAkPaes/2dsndhaA==,type:str]
    pgp:
        - created_at: "2025-09-22T12:08:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7HkzTbKNKEvAQ//f0KsThdFng4qDOOJssQPgubtD05x5ZsE4EoNhqTAVqf6
            t/tOJTB5P+FLuKhXeU90dkmeR8F437eoO14lFsrsEGdGnqd4es8IMRkIei8ocPS1
            rWXmwTVtFrw6m3BJBJYCgQBpVy6BkabYcv2qs573z02rle08e85VPNFZGnrBKoGc
            xhz+EVHT2Tnf2XtxlsvfTC6+JK0O/xMp1dhzQj8iGehTaGR6wOHZh36AoQKfFfUr
            xQsBuIfYUYiX5Lgk+yihBk9ufwgK62vvHWGSIR2AA/nnmbM+iWJ8cxPUYBCYp+WB
            Ef+HTu69qaiu5k5Pm72ivvYnkLtVa+JvBRWLjp6P2EiQBXVzlr8NNFGNKa0CsQrw
            7UwRA8x1JtLeIaalqsmEr64NlLCigN49b2W1L5/O80u5xthRIf+94RSZRvzVzbeF
            KhXcED0woKi5MGOT5Y4l9+s8/8S/ZpoyCV2FMXIg03MHeOERC+nlXKQbA5vJrQrN
            zl5dRc39eICMheDN/anmmdwVE7pR4IobzoWK2b2cyAr2zQgsJlcBtvWoqHu7v8/t
            mSwX6zC/ruB3f52ZdtRxvdCfcAlS0Dc0hpE1VgLe/32rDVTDJ97zSNz9YoG/3QJY
            3ylLzchgrefuRtJ8ROfSLE9NVvWjRAxKmEQKSSjpjv/hxBXjI+RWysx13noRA8fU
            aAEJAhCCOqnMFQxsNCLThfzfD2shdnPwMKcLbeMYmYYXJ96Ds9cAKEaBKjukm6eV
            8Jxc9tEW+pgjqbJ7j15PtBkdwYdJOdN296iQrXlgQ2/wLhVkgP0GZgxza2Ql5BIE
            59FEPRG+H/88
            =DxmN
            -----END PGP MESSAGE-----
          fp: C2C715BB173803D1A33C0B9E64D72306B5CEADB8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
