apiVersion: v1
kind: Secret
metadata:
    name: redis-secret
    namespace: redis
data:
    password: ENC[AES256_GCM,data:0PWzsfB48hOq3/v3L/IkQtvOoFV9HfBCxUEt+w==,iv:EyV0xFKQC5/5wz8EcfabZ0yHyQes3vyFPnIwC4Ve+3s=,tag:iAR4Dy8KWWu+IJkJFGvb6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-09-23T09:56:02Z"
    mac: ENC[AES256_GCM,data:PPQu3AjAEmHTO7O6qk074qNpXZsb/GLw8zlYLs6eQaWNbvwzC9I2JelxpwGR4RgaPQNnO5Wc+JzXDAAPs7EoEbtnYPcEG4o1Jn31Z1saqKfutR/nyZ+bGtXGllDVo/31iYb+R/F+GuhenK2SmU3ODEQyo4VwVRa/0vNrwnjlYSw=,iv:QJvDzr9pm97EH1VkHQe3ThiXoqIFc9mknhxKVW7Hm2Y=,tag:/Y0e3eZRol0j0eXLqMALVQ==,type:str]
    pgp:
        - created_at: "2025-09-23T09:56:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7HkzTbKNKEvAQ/9GQgZmRDkIoEnmYxAC5NGdQ/a8lirpQzUTesaFzJGd6oI
            0If/kNdNkaOPoelxAZmICK5qrD81N6mNw0Faf24hvRjsp5vyuG721BuGW4qxbmSt
            Fq435VcvIw5mH7YFLDwte5CPrShXckNgshrdnOJPD189nimyQbCll2A3bpkh4ZP6
            HBbo7cv/B8FMZOfDZPoEi/J0BCa21B4U9HZedHVeOsrkq2oZRuUMOkwu73YxNuDV
            ilu/jEOC23nUJ7mW+hXtvI16ymVnEAEE6dPUB06AZcd9Mqdg06UY5xStVFE1MzcC
            42m8pkAmwzNVYmO6YvNtIzzGzDieo8PFkH6xw6wPigMWZac5NMtw3hDnKJokcMp6
            naWY7GWU8zNnOm1zY/fGOeL0jEtU4AHOnzOIruE0DuF3eJ3RrZDiPRCSLI9YjHip
            nhgSypr+p6BUvp4TU8UcPUqYVjC8cugBeCalOBTTmDePwpgEJCUwVJe0IYsBUnKd
            vo+O4P+8XwDqlELM2CQcT88emgwvmBFfn2c2o5VJN4PJY2x6Yo9brGxJt4y5heWx
            dqMMuDCY5md2sh8s8PZ6qmkMlnDiWxzfT5p6+LXzjogafrINXeAoj9mQj8rHfPTs
            TUB9h4yfrc6zcfS72pWhjoZHrw8Zqcp/F2wRpoKGVxovGmBMNYAybkID/EsYGOPU
            aAEJAhDZLudsuigAYriyoAjhBEUeBEnkyUVDmlI6P3sIncHdnK9JjkFT9nvVF3UI
            cVbCQalzSHeOplD3PVp82CDV4B9FwqqaCbvHXOg+p/pLbtShV3mQMhXiyO3IBMLO
            PWvaSzO+Rcq/
            =zJSc
            -----END PGP MESSAGE-----
          fp: C2C715BB173803D1A33C0B9E64D72306B5CEADB8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
