apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
data:
    secretkey: ENC[AES256_GCM,data:rGBnvrkt9mh9ACNwclqDrruwsT3s2UAybY2XWRz0iyXRJ4DOLKmk9J0vNz8y7sFalXiYJIXqYpiAykW+4t1lbs4wch0=,iv:wKJOF+tKnqXlxHAQGWMbgQr+UobGPAYovF0xerYwhfE=,tag:DCqMCT5cjBnr3DMi9gMbhg==,type:str]
    username: ENC[AES256_GCM,data:/Ie0FvdR51Os987r,iv:Km1ivZGXwqSz7xOnqwR/NVeoUIlrztt+KdiepuGFEic=,tag:wU6rPBuROz8R99cwlaNEbw==,type:str]
    password: ENC[AES256_GCM,data:q93lH+NUXlocJurOQpPrmxxURMUZadVsSLNDEMZLq8I=,iv:KEloSrwnciVU9FikUlL8aJ9jVPRBoa9FTPL6cHorenU=,tag:Gz6RVNEm2P7geVyA5IP2Qw==,type:str]
    redis-password: ENC[AES256_GCM,data:ogikgIQnWCKFqeQ3uLkyq6yX94DgjkOSPkHs+w==,iv:dpAy9x/mbBDu4giyknbj9KLmZHo5x2WxnaBAhL0V7tU=,tag:tgHu923eoAI8yh1pBf+nzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-09-23T10:10:48Z"
    mac: ENC[AES256_GCM,data:VBcQOJxldXeewUP7cHPiRrQHWNnR3pc+PXHQWcmpedaWuH/VTTh3JW+fCJSZVpUxTnbmQ+2iq+uFr287Z3UmvM04nf21bvMDnR11KzIXvuM85rCRlfKhjhvSFOALpzHbZ4ZX7WtSZgyOhcf7TiEJxbD9da+YRkCCwI2bFwBiLXg=,iv:nx+evvtT1SXUmZ6J+giWkjhym3csyCjgdVkACXKfV5M=,tag:CZPUi1Wc5YlKHDbHVGmz7g==,type:str]
    pgp:
        - created_at: "2025-09-23T10:10:48Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7HkzTbKNKEvAQ/7Bb3GgOFF3Q/+dCgtJHHZRpq6o4GbdCKRGHT/NlBl81Id
            Dh3WSoOPC3Yb9/l5OhgO7VZ9CUYlVvyNIdwbQE5uZE7mMrtmVssR7aF+qkIWc4tD
            k+JoHpmWUat/Hhc5T+OPJ7rCtX1TjIb5HpIncJ1Q4kk/pMKC7fL52xjwM5zTTp9p
            LXurunh0ZMvWDUbRQDgKi9CKITn7YyeIGQAwDN2a2LRd2l1E3mCPBMIqCL2VQ3x1
            WPzr1Z1nmftYSwXkE0Wv/rsjG6WTdDRt2/webbSYWPKvArTrpgnWQNGTyATty6KU
            BYGDT90nSiSPK2ENwJAvwTezTId3qdhWxVVh04eYOfpgwKj197ms7bCqwh7E6S5S
            nP+IlZjKihA+U9QwiTxCDiALsm9yS++9S8hygtoC/D3wPNzJZ3dTrgNzyiP0R6Bj
            qsc6ZK0AK2iHNQgI4bZU5mBMJdlYVp7xMkVyJ43f8vswEv34XAl80ZSmR7ubVdbv
            zOlBZ9N3RynbY0ZwbyjTpko/Zuxn7V5XtglSzJ9NXkBOOiF+7HyYfFOu4AaAhmY+
            HY4KPM50L5rhRTHTh6vyhIwpJJTa+WDSP9gNTQHDoiQfA8bTR1ASnKrSx7whQCeS
            d9hhbfYV2PIC7CpD3wTxDbZd+DQM/aYqdb3Gy4PSA5vh41daIGcGaJzx3hAevXPU
            aAEJAhBVg8OIcgL5pugli1AaaLz68q0mbrcysMQx0ZNKuQH5+mZxIFr0hgGqZ5sg
            iTZb6UQK8dUBbdEUWUbMxwlTdMLZHUW3/AUjQY7y7VTeI83zvPh6eRCV+hRM+Ewl
            o8TYZm0OSYz9
            =8COB
            -----END PGP MESSAGE-----
          fp: C2C715BB173803D1A33C0B9E64D72306B5CEADB8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
